services:
  frontend:
    platform: linux/amd64
    image: ${DOCKER_USERNAME}/${PACKAGE_NAME}:${PACKAGE_VERSION}
    container_name: ${PACKAGE_NAME}
    env_file:
      - .env
    expose:
      - "4000"
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
